version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: novel_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: novel_platform
      MYSQL_USER: novel_user
      MYSQL_PASSWORD: novel_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - novel_network

  redis:
    image: redis:alpine
    container_name: novel_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - novel_network

volumes:
  mysql_data:
  redis_data:

networks:
  novel_network:
    driver: bridge 